### ISSUE TITLE
Activating extension ghmcadams.lintlens failed due to an error: rules.js:22:15

### ISSUE THREAD

**Issue by frck006** [ghmcadams/vscode-lintlens#18]
Hi,

With VCS 1.41.1 and Windows 10, this extension doesn't start with this error:
```
[2019-12-23 08:14:24.218] [exthost] [error] t
    at c:\Users\fmar\.vscode\extensions\ghmcadams.lintlens-2.7.0\src\rules.js:22:15
    at Module.<anonymous> (c:\Users\fmar\.vscode\extensions\ghmcadams.lintlens-2.7.0\src\rules.js:6:15)
    at n (c:\Users\fmar\.vscode\extensions\ghmcadams.lintlens-2.7.0\webpack\bootstrap:19:22)
    at c:\Users\fmar\.vscode\extensions\ghmcadams.lintlens-2.7.0\webpack\bootstrap:83:10
    at Object.<anonymous> (c:\Users\fmar\.vscode\extensions\ghmcadams.lintlens-2.7.0\dist\extension.js:1:933)
    at Module.o._compile (c:\Users\fmar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:749)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Function.t._load (c:\Users\fmar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:818:851)
    at Function.n._load (c:\Users\fmar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:789:164)
    at Function.i._load (c:\Users\fmar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:785:618)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Function.s [as __$__nodeRequire] (c:\Users\fmar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:32:963)
    at d._loadCommonJSModule (c:\Users\fmar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:790:289)
    at d._doActivateExtension (c:\Users\fmar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:694:547)
    at d._activateExtension (c:\Users\fmar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:693:582)
    at Object.actualActivateExtension (c:\Users\fmar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:691:534)
    at d._activateExtension (c:\Users\fmar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:517:21)
    at c:\Users\fmar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:516:632
    at Array.map (<anonymous>)
    at d._activateExtensions (c:\Users\fmar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:516:620)
    at d.activateById (c:\Users\fmar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:514:709)
    at d._activateById (c:\Users\fmar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:692:345)
    at d._activateIfGlobPatterns (c:\Users\fmar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:698:162)
    at async Promise.all (index 1)
    at async Promise.all (index 85)

```

In your code, it seems to have a problem to get workspace directory for eslint:
```
function loadRules() {
    const eslintPackagePath = getWorkspaceDir('./node_modules/eslint');

    if (!eslintPackagePath) {
        throw new MissingESLintError();
    }

```

Regards

**Comment by zachhardesty7** [comment]
Also having this issue unfortunately...

UPDATE: this issues appears to only occur on Windows. Also, the file-type MUST be set to "javascript" and NOT "javascriptreact."
